
name: Fancode Fetch and Upload Data

on:
  schedule:
    - cron: '0,15,30,45 * * * *' # Runs at 0, 15, 30, and 45 minutes past every hour
  push:
    branches:
      - main

jobs:
  fetch_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }} # Use the GitHub token for authentication

    - name: Remove existing files
      run: |
        rm -f fancode.json fancode.m3u

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/drmlive/fancode-live-events.git

    - name: Stash any local changes
      run: |
        git stash --include-untracked || echo "Nothing to stash"

    - name: Pull the latest changes
      run: |
        git pull --rebase origin main || echo "Rebase not needed"

    - name: Fetch data from APIs
      run: |
        curl -o fancode.json ${{ secrets.FANCODE_API_URL }}
        curl -o fancode.m3u ${{ secrets.FANCODE_M3U_URL }}

    - name: Add, commit, and push changes
      run: |
        # Exclude the workflow file from being committed
        git add fancode.json fancode.m3u
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Fetch latest data"
          git pull --rebase origin main # Ensure local repo is up-to-date
          git push origin main
        fi
